// ROUGE-V regression: real NVIDIA PTX must translate end-to-end.
//
// Everything else in the suite feeds our own hand-written .ptx files, whose
// formatting and opcode mix differ from what nvcc actually emits. This test
// closes that gap: it compiles real CUDA C with the vendor's own nvcc, takes
// the PTX it produces, and pushes it through ptx2ir -> clang.
//
// Skipped (not failed) when no nvcc is installed, so the suite still runs on a
// machine without the CUDA toolkit.
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>

namespace {

std::string slurp(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  if (!f) return "";
  std::stringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

int failures = 0;

void check(bool ok, const std::string& what) {
  if (ok) {
    std::printf("ok:   %s\n", what.c_str());
  } else {
    std::printf("FAIL: %s\n", what.c_str());
    ++failures;
  }
}

}  // namespace

int main(int argc, char** argv) {
  const std::string nvcc = (argc > 1) ? argv[1] : "nvcc";
  const std::string src = std::string(RougeTestDir) + "/real_nvcc.cu";
  const std::string outPtx = std::string(RougeTestDir) + "/real_nvcc.ptx";
  const std::string outIr = std::string(RougeTestDir) + "/real_nvcc.ll";
  const std::string outObj = std::string(RougeTestDir) + "/real_nvcc.o";

  if (slurp(src).empty()) {
    std::printf("SKIP: %s not found\n", src.c_str());
    return 77;  // ctest "skipped return code"
  }
  const int rc = std::system(
      (nvcc + " -arch=sm_75 -ptx " + src + " -o " + outPtx + " 2>&1").c_str());
  if (rc != 0) {
    std::printf("SKIP: nvcc unavailable or rejected -arch=sm_75 (rc=%d)\n", rc);
    return 77;
  }
  const std::string ptx = slurp(outPtx);
  check(ptx.find("Generated by NVIDIA") != std::string::npos,
        "nvcc produced vendor PTX");

  // A real nvcc signature is one line; our parser must accept it.
  check(ptx.find(".visible .entry") != std::string::npos &&
            ptx.find(".param") != std::string::npos,
        "vendor PTX uses the one-line .entry signature");

  const std::string ptx2ir = std::string(RougePtx2Ir);
  const int rc2 = std::system(
      (ptx2ir + " " + outPtx + " " + outIr + " 2>&1").c_str());
  if (rc2 != 0) {
    std::printf("FAIL: ptx2ir rejected vendor PTX (rc=%d)\n", rc2);
    return 1;
  }
  const std::string ir = slurp(outIr);
  check(ir.find("define void @") != std::string::npos,
        "ptx2ir emitted an LLVM function for vendor PTX");
  check(ir.find("external global") != std::string::npos,
        "__device__ globals were declared and addressed");
  check(ir.find("__rouge_syncthreads") != std::string::npos,
        "bar.sync lowered to the runtime barrier call");
  check(ir.find("atomicrmw") != std::string::npos,
        "atomicAdd lowered to atomicrmw");

  const std::string clang = (argc > 2) ? argv[2] : "clang";
  const int rc3 = std::system((clang + " -O2 -c " + outIr + " -o " + outObj +
                               " 2>&1").c_str());
  check(rc3 == 0, "clang compiled the translated IR to a native object");

  if (failures) {
    std::printf("%d vendor-PTX checks FAILED\n", failures);
    return 1;
  }
  std::printf("all vendor-PTX checks passed (nvcc -> ptx2ir -> clang)\n");
  return 0;
}
